### ISSUE TITLE
"Show whole diff of working tree" does not work

### ISSUE THREAD

**Issue by carlfriedrich** [jacekkopecky/vscode-whole-diff#2]
Running the "Show whole diff of working tree" command does not work in my environment:

![grafik](https://user-images.githubusercontent.com/45259958/197476151-69301073-6b09-4dfc-8901-b8ba0a94dec4.png)

![grafik](https://user-images.githubusercontent.com/45259958/197476329-650fee8b-deb8-4c44-a862-3e31b89ecb48.png)

My workspace is a folder in a WSL remote session.

**Comment by jacekkopecky** [comment]
Confirmed; I always open it with the icon so I missed this.

Does it work for you if you click the book icon in Source Control by Changes?

**Comment by carlfriedrich** [comment]
Thanks for your feedback. Yes, the book icon works.

**Comment by jacekkopecky** [comment]
0.2.3 fixes this, thanks for reporting!

**Comment by jacekkopecky** [comment]
@carlfriedrich please confirm whether that's fixed it for you

**Comment by carlfriedrich** [comment]
@jacekkopecky Great, thanks for the quick fix! Works for me now!
